# hyperparam_config.yaml
studySpec:
  metrics:
  - metricId: val_loss
    goal: MINIMIZE
  parameters:
  - parameterId: learning_rate
    doubleValueSpec:
      minValue: 0.00001
      maxValue: 0.001
    scaleType: UNIT_LOG_SCALE
  - parameterId: hidden_dim
    discreteValueSpec:
      values: [64, 128, 256]
  - parameterId: num_encoder_layers
    discreteValueSpec:
      values: [3, 4, 5]
  - parameterId: num_decoder_layers
    discreteValueSpec:
      values: [3, 4, 5]
  - parameterId: masking_ratio
    doubleValueSpec:
      minValue: 0.3
      maxValue: 0.6
  - parameterId: batch_size
    discreteValueSpec:
      values: [16, 32, 64]
  algorithm: BAYESIAN_OPTIMIZATION
  
  # early stopping policy
  medianAutomatedStoppingSpec:
    useElapsedDuration: true
  measurementSelectionType: BEST_MEASUREMENT
  
maxTrialCount: 20
parallelTrialCount: 4
maxFailedTrialCount: 5